config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#index"
  post 'homes/guest_sign_in', to: 'homes#new_guest'
  get 'search' => 'movies#search'


  resource :profile, only:[:new,:create]
  resource :timeline, only:[:show]

  resources :favorites, only:[:index]

  resources :movies, only:[:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :comments, only: [:index, :new, :create]
    resources :spoilers, only: [:index, :new, :create]
    resource :like, only: [:show, :create, :destroy]
  end

  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :feelings, presence: true
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
  
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :movie
    belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many_attached :eyecatch
  has_many :comments, dependent: :destroy
  has_many :spoilers, dependent: :destroy
  has_many :likes, dependent: :destroy

  belongs_to :user
  
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :entertainment, presence: true
  validates :genre, presence: true
  

  def like_count
    likes.count
  end

  def avg_score
    unless self.comments.empty?
      comments.average(:star).
    else
      0.0
    end
  end

 def avg_score_percentage
   unless self.comments.empty?
     comments.average(:star).round(1).to_f*100/5
   else
     0.0
   end
 end

 #コメント件数
 def comment_count
  comments.count
 end

 #検索機能
  def self.search(search) 
    if search 
      Movie.where(['title LIKE ?', "%#{search}%"])
    else
      Movie.all 
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

end

app/models/spoiler.rb
class Spoiler < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true


  has_one :profile, dependent: :destroy
  has_one_attached :avatar
  
  has_many :movie,dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorite_movies, through: :likes, source: :movie
  has_many :comments, dependent: :destroy
  has_many :spoilers, dependent: :destroy
  has_many :liked_timelines, through: :likes, source: :timeline

  def has_liked?(movie)
    likes.exists?(movie_id: movie.id)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = 'ゲスト'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @movie = Movie.find(params[:movie_id])
    @comment = @movie.comments
  end


  def new
    @movie = Movie.find(params[:movie_id])
    @comment = @movie.comments.build
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @comment = @movie.comments.build(movie_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to movie_comments_path(@movie), notice:'コメントを追加'
    else
      flash.now[:error] = '保存に失敗しました' 
      render :index
    end
  end

  private
  def movie_params
    params.require(:comment).permit(:feelings, :rate).merge(user_id: current_user.id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @movies = current_user.favorite_movies
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
  
  def new_guest
    user = User.find_or_create_by(email: 'guest@example.com') do |user|
        user.password = SecureRandom.urlsafe_base64
        user.username = 'ゲスト'
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  def show
    movie = Movie.find(params[:movie_id])
    like_status = current_user.has_liked?(movie)
    render json: { hasLiked: like_status }  
  end

  def create
    movie = Movie.find(params[:movie_id])
    movie.likes.create!(user_id: current_user.id)

    render json: { status: 'ok'}
  end

  def destroy
    movie = Movie.find(params[:movie_id])
    like = movie.likes.find_by!(user_id: current_user.id)
    like.destroy!
    
    render json: { status: 'ok'}
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery :except => [:destroy]
  
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = current_user.movie.build
  end

  def create
    @movie = current_user.movie.build(movie_params)
    if @movie.save
      redirect_to movies_path, notice: '保存できました'
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movie_path(@movie), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    movie = current_user.movie.find(params[:id])
    movie.destroy!
    redirect_to movies_path, notice: '削除に成功しました' 
  end

  def search
    @movie = Movie.search(params[:search])
    @keyword = params[:search]
    render "index"
  end


  private
  def movie_params
    params.require(:movie).permit(:title, :eyecatch, :story, :entertainment, :genre).merge(user_id: current_user.id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  

  def new
    @profile = current_user.build_profile
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
        redirect_to root_path, notice: 'プロフィールを作成できました'
    else
        flash.now[:eoor] = '更新に失敗しました'
        render :new
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:username)
  end
end

app/controllers/spoilers_controller.rb
class SpoilersController < ApplicationController
  before_action :authenticate_user!
  def index
    @movie = Movie.find(params[:movie_id])
    @spoiler = @movie.spoilers
  end

  def new
    movie = Movie.find(params[:movie_id])
    @spoiler = movie.spoilers.build
  end

  def create
    @movie = Movie.find(params[:movie_id]) 
    @spoiler = @movie.spoilers.build(spoiler_params)
    if @spoiler.save
      redirect_to movie_path(@movie), notice: 'ネタバレを追加しました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def spoiler_params
    params.require(:spoiler).permit(:content) .merge(user_id: current_user.id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end

  def terms; end

  def privacy_policy; end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def show
    @movies = Movie.find(Like.group(:movie_id).order('count(movie_id) desc').pluck(:movie_id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
  def add_active_class(path)
    'active' if current_page?(path)
  end
end

app/views/comments/index.html.haml
= render 'commons/comments'

app/views/commons/_comments.html.haml
.container
  .header_comment
    %div
      %p.page_title 作品レビュー

  .comment
    -  @comment.each do |comment|
      .comment_content_username
        %p= comment.user.username
      .comment-feelings
        %p
          内容:#{comment.feelings}
        %p
          評価:#{comment.rate}点

      %div{:id => "star-rate#{comment.id}"}
      :javascript
        $('#star-rate#{comment.id}').raty({
          size      : 36,
          starOff   : '#{asset_path('star-off.png')}',
          starOn    : '#{asset_path('star-on.png')}',
          half      : false,
          readOnly: true,
          score: #{comment.rate},
        });
      %hr   

= form_with(model:[@movie, @comment],url:movie_comments_path, local: true) do |f|
  .comment_form
    .comment_form_container
      %label.comment_create_icon
        = f.label :feelings, 'コメント'
        = f.text_area :feelings, class: 'comment_text'
    .field
      #star.form-group.row
        = f.label :rate,'評価', class:'col-md-3 col-form-label'
        
      :javascript
        $('#star').raty({
          size     : 36,
          starOff:  '#{asset_path('star-off.png')}',
          starOn : '#{asset_path('star-on.png')}',
          scoreName: 'comment[rate]',
          half: false,
        });

  .comment_submit
    = f.submit '保存', class: 'btn-primary'

= javascript_pack_tag 'raty'

  

app/views/commons/_footer.html.haml
.container
  = link_to '利用規約', terms_path, class:'static_set'
  = link_to 'プライバシーポリシー', privacy_policy_path, class:'static_set'
  .static_set
    %p Copyright © 2022. ムビドラ

app/views/commons/_movies.html.haml
.container
  - @movies.each do |movie|
    = link_to movie_path(id: movie.id) do
      .movie_list
        - movie.eyecatch.each do |eyecatch| 
          = image_tag eyecatch, class: 'movie_content_image'
      .movie_name
        %p= movie.title
        %div{:id => "rate#{movie.id}"}
      .movie_comments
        %p 「レビュー」
        %span= movie.comment_count
        %p 件
      .movie_liked
        %p 「観たい!」
        %span= movie.like_count
        %p 件
    :javascript
        $('#rate#{movie.id}').raty({
        size: 36,
        starOff: '#{asset_path('star-off.png')}',
        starOn: '#{asset_path('star-on.png')}',
        harf: true,
        readOnly: true,
        score: #{movie.comments.average(:rate).to_f.round(1)}
      });

app/views/commons/_rate_average.html.haml
%div{:id => "star-rate#{@comment.id}"}
  :javascript
    $('#star-rate#{@comment.id}').raty({
      size      : 36,
      starOff   : '#{asset_path('star-off.png')}',
      starOn    : '#{asset_path('star-on.png')}',
      half      : false,
      readOnly: true,
      score: "#{@comment.average(:rate).to_f.round(1)}",
    });

app/views/commons/_tabs.html.haml
.tabs
  .tabs_item{class: "#{add_active_class(movies_path)}"}
    = link_to movies_path do
      映画・ドラマ一覧
  .tabs_item{class: "#{add_active_class(timeline_path)}"}
    = link_to timeline_path do
      タイムライン
  .tabs_item{class: "#{add_active_class(favorites_path)}"}
    = link_to favorites_path do
      お気に入り

app/views/favorites/index.html.haml
.container
  = render 'commons/tabs'
  %h2
    あなたが気になる作品
  = render 'commons/movies'

app/views/home/index.html.haml
.container-bg
  .bg
    %p.title ムビドラ
    %h2.title 自分の一番好きな映画・ドラマを投稿して
    %h2.title 本当に面白い作品「だけ」を皆に広めよう!!
    .bg_text
      %p= link_to 'ユーザー登録はこちら', new_user_session_path, class:'btn-secondary'
      %p= link_to '映画・ドラマ一覧', movies_path, class:'btn-secondary'

= render 'commons/footer'
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Movidra
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          = link_to :back do
            = image_tag 'back.svg', class: 'header_back'
        %p.header_pageTitle
          = link_to 'ムビドラ', movies_path
      
      - if !current_page?(root_path) 
        .search-form
          = form_with url:search_path, method: :get, local:true  do |f|
            = text_field_tag :search, params[:search],:placeholder => "作品名を入力",:value => ""
            = submit_tag "検索", :title => nil

      - if user_signed_in?
        = link_to 'ログアウト', destroy_user_session_path,data: {method: 'delete', confirm:'ログアウトしてもよろしいですか？'}
      - else
        = link_to 'ログイン', new_user_session_path
    


    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/movies/edit.html.haml
.container
  = form_with(model:@movie, url:movie_path(@movie), method:'put', local:true ) do |f|
    %div
      = f.label :eyecatch, '画像'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :story, 'ストーリー'
    %div
      = f.text_area :story
    .actions
      = f.submit '保存', class: 'btn-primary'

app/views/movies/index.html.haml
.container
  = render 'commons/tabs'
  = render 'commons/movies'
  = link_to new_movie_path do
    .float_btn
      %i.fa.fa-plus

app/views/movies/new.html.haml
.container
  %ul
    -@movie.errors.full_messages.each do |message| 
      %li= message
  = form_with(model:@movie, url:movies_path, method:'post', local:true ) do |f|
    %div
      = f.label :eyecatch, '画像'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :entertainment, '娯楽'
    %div
      = f.select :entertainment,  [ ["映画"], ["ドラマ"]],  prompt: "娯楽を選択してください"
    %div
      = f.label :genre, 'ジャンル'
    %div
      = f.select :genre,  [ ["アクション"], ["SF"],["スリラー"], ["アドベンチャー"], ["ファンタジー"], ["ホラー"], ["サスペンス"], ["ミステリー"], ["コメディ"], ["恋愛"], ["ファミリー"], ["ミュージカル"], ["アニメ"], ["その他"]], prompt: "ジャンルを選択してください"
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :story, 'ストーリー'
    %div
      = f.text_area :story
    .actions
      = f.submit '保存', class: 'btn-primary'

app/views/movies/show.html.haml
.container
  .movie
    .movie_nav
      .movie_title#movie-show{data: {movie_id: @movie.id}}
        %p= @movie.title
      - if user_signed_in? && current_user.movie.exists?(id: @movie.id)
        .dropdown
          = image_tag 'actions.svg', class: 'dropbtn'
          .dropdown-content.mini
            = link_to '編集する', edit_movie_path(@movie)
            = link_to '削除する', movie_path(@movie), data: { method:'delete', confirm:'本当に削除してもよろしいですか？'}
      .movie_nav_image
      - @movie.eyecatch.each do |eyecatch| 
        = image_tag eyecatch, class: 'movie_content_image'
      .movie_genre
        %p <ジャンル>
      .movie_frame
        %p= @movie.entertainment
        %p ・
        %p= @movie.genre
      .movie_story
        %p <ストーリー>
        %p= @movie.story
     
      
  .movie_content
    - if user_signed_in?
      .movie_heart.hidden.active-heart
        = image_tag 'heart-active.svg', class:'like_icon'
        %p 観たい
      .movie_heart.hidden.inactive-heart
        = image_tag 'heart.svg', class:'like_icon'
        %p 観たい

    .movie_comment
      = link_to movie_comments_path(@movie.id) do
        = image_tag 'comment3.png', class:'movie_icon'
        %p 作品レビュー

    .movie_share
      = link_to "https://twitter.com/share?url=#{request.url}", title: 'Twitter', target: '_blank' do
        = image_tag 'twitter.png', class: 'movie_icon'
        %p 共有

    .movie_secret
      = link_to movie_spoilers_path(@movie.id) do
        = image_tag 'netabare.png', class: 'movie_icon'
        %p 考察部屋

= javascript_pack_tag 'movie'

app/views/profiles/new.html.haml
.container
  = form_with(model:@profile, url:profile_path, method:'post', local:true ) do |f|
    %div
      = f.label :avatar, 'アバターを選択', class: 'post_image'
    %div
      = f.file_field :avatar, class: 'image_form'
    %div
      = f.label :username, '名前'
    %div
      = f.text_field :username
    .actions
      = f.submit 'SUBMIT', class: 'avatar_submit_btn'

app/views/spoilers/index.html.haml
.container
  .header_comment
    %div
      %p.page_title ネタバレ

  .spoiler
    -  @spoiler.each do |spoiler|
      .spoiler-content
        %p= spoiler.user.username
        %p= spoiler.content
      %hr

  = link_to new_movie_spoiler_path do
    .float_btn
      %i.fas.fa-comment-plus 

app/views/spoilers/new.html.haml
.container
  = form_with(model: @spoiler, url: movie_spoilers_path(@spoiler.movie), local: true) do |f|
    %div 
      = f.label :content, 'ネタバレ投稿'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/static_pages/privacy_policy.html.haml
.container
    %h1 プライバシーポリシー
    %p 【ムビドラ-】運営者（以下，「運営者」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
    %h1 第1条（個人情報）
    %p 「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。
    %h1 第2条（個人情報の収集方法）
    %p 運営者は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,運営者の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。
    %h1 第3条（個人情報を収集・利用する目的）
    %p 運営者が個人情報を収集・利用する目的は，以下のとおりです。
    %ol
    %li 運営者サービスの提供・運営のため
    %li ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）
    %li ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び運営者が提供する他のサービスの案内のメールを送付するため
    %li メンテナンス，重要なお知らせなど必要に応じたご連絡のため
    %li 利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため
    %li ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため
    %li 有料サービスにおいて，ユーザーに利用料金を請求するため
    %li 上記の利用目的に付随する目的
    %h1 第4条（利用目的の変更）
    %ol
    %li 運営者は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。
    %li 利用目的の変更を行った場合には，変更後の目的について，運営者所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。
    %h1 第5条（個人情報の第三者提供）
    %ol
    %li 運営者は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。
    %ol
        %li 人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき
        %li 公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき
        %li 国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき
        %li 予め次の事項を告知あるいは公表し，かつ運営者が個人情報保護委員会に届出をしたとき
        %ol
        %li 利用目的に第三者への提供を含むこと
        %li 第三者に提供されるデータの項目
        %li 第三者への提供の手段または方法
        %li 本人の求めに応じて個人情報の第三者への提供を停止すること
        %li 本人の求めを受け付ける方法
    %li 前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。
    %ol
        %li 運営者が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合
        %li 合併その他の事由による事業の承継に伴って個人情報が提供される場合
        %li 個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合
    %h1 第6条（個人情報の開示）
    %ol
    %li 運営者は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。
    %ol
        %li 本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合
        %li 運営者の業務の適正な実施に著しい支障を及ぼすおそれがある場合
        %li その他法令に違反することとなる場合
    %li 前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。
    %h1 第7条（個人情報の訂正および削除）
    %ol
    %li ユーザーは，運営者の保有する自己の個人情報が誤った情報である場合には，運営者が定める手続きにより，運営者に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。
    %li 運営者は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。
    %li 運営者は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。
    %h1 第8条（個人情報の利用停止等）
    %ol
    %li 運営者は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。
    %li 前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。
    %li 運営者は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。
    %li 前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。
    %h1 第9条（プライバシーポリシーの変更）
    %ol
    %li 本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。
    %li 運営者が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。
    %p 以上

app/views/timelines/show.html.haml
.container
  = render 'commons/tabs'
  = render 'commons/movies'

  = link_to new_movie_path do
    .float_btn
      %i.fa.fa-plus